Design Cleanup
stepzen-samples/json2sdl-frontend pull request #6
Opened 2021-11-23 21:18 UTC by mtrythall

This does a first pass of design clean up. It does the following:

1. Removes unnecessary CSS code
2. Adds appropriate logo files
3. Simplifies some of the layout code
4. Adds the social nav and footer
5. Slims down the aesthetic a little
6. Introduces missing CSS files, like those for reset

2021-11-23 22:15 UTC, SamuelGHill requested changes

2021-11-23 22:15 UTC, SamuelGHill commented on index.html
> -                  Start with an example
Change this

```
<button
              id="form-button"
              @click.self="handleClick()"
              class="button color11"
            >
              <span>Start with an example</span>
            </button>
```

to this and the generator for start with an example will work. The convert button still works.
```
<button
              id="form-button"
              class="button color11"
            >
              <span
                @click.self="handleClick()"
              >Start with an example
              </span>
            </button>
```

2021-11-23 22:15 UTC, SamuelGHill commented on index.html
> -                  Start with an example
I poorly added tabs to that. Please clean up when copying and pasting

2021-11-23 22:15 UTC, SamuelGHill commented on index.html
> +              <div class="codedemo-display">
The responsiveness of the code is not the same as the json2sdl right now. Maybe something got deleted that was needed to keep the responsiveness?

Example is 

1. When I go to mobile, the code does not appear in the input / json side.
2. When the code is generated on desktop, the div surrounding the code editor enlarges beyond the size of the code, and does not properly wrap it. Click the "example" button and scroll the example json and you will see. I could not pin point what was deleted that made this work.

2021-11-24 02:54 UTC, mtrythall commented on index.html
> -                  Start with an example
Makes sense. No sense in worrying about bubbling it up.

2021-11-24 16:22 UTC, mtrythall commented on index.html
> +              <div class="codedemo-display">
@SamuelGHill This ought to be better, but not perfect. Ace Editor is doing some sizing that I think was resulting in double scrolling before (and now). The second issue is still sort of there, but not that bad, and not such that I think this should block from going up. Give it a look and LMK what you think.

2021-11-29 16:29 UTC, SamuelGHill approved these changes
LGTM

2021-11-29 16:29 UTC, merged